/**
 * OSTEOPATHY TECHNIQUE REGISTRY — 120 Techniques
 * Categories: Joint Mobilization(25), HVLA/Manipulation(20, chiropractic-derived), Muscle Energy(25),
 *             Myofascial Release(20), Visceral(15), Cranial(15)
 * Note: HVLA techniques originate from chiropractic. Included for completeness;
 *       isChiropracticDerived=true on all HVLA entries — UI can badge/filter accordingly.
 * Videos: /public/exercise-videos/{id}.mp4
 * Two-avatar system: therapist + patient on treatment table.
 */

export interface OsteopathyTechnique {
  id: string;
  name: string;
  region: string;
  techniqueType: "joint-mobilization" | "hvla" | "muscle-energy" | "myofascial-release" | "visceral" | "cranial";
  /** HVLA techniques originate from chiropractic — use with osteopathic training context */
  isChiropracticDerived?: boolean;
  patientPosition: string;
  therapistPosition: string;
  description: string;
  animationPrompt: string;
  videoSrc: string;
  tip?: string;
}

const V = (id: string) => `/exercise-videos/${id}.mp4`;

export const OSTEOPATHY_REGISTRY: OsteopathyTechnique[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // JOINT MOBILIZATION — 25 techniques
  // ═══════════════════════════════════════════════════════════════════════════

  { id:"osteo-cervical-mob-c0-c1", name:"C0-C1 Occipito-Atlantal Mobilization", region:"Cervical", techniqueType:"joint-mobilization", patientPosition:"Supine", therapistPosition:"At head of table", description:"Gentle AP glide of the atlas beneath the occiput restoring upper cervical flexion-extension.", animationPrompt:"3D medical animation. Two avatars. Patient supine, therapist standing at head of table. Therapist cradles occiput with both hands, applies subtle anterior glide of atlas. C0-C1 joint highlighted amber. Glide arrows. 8-second loop.", videoSrc:V("osteo-cervical-mob-c0-c1"), tip:"Assess occipital condyle symmetry before applying force." },

  { id:"osteo-cervical-mob-c1-c2", name:"C1-C2 Atlanto-Axial Mobilization", region:"Cervical", techniqueType:"joint-mobilization", patientPosition:"Supine", therapistPosition:"At head of table", description:"Rotational mobilization of C1-C2 — 50% of cervical rotation occurs here. Restores rotational restriction.", animationPrompt:"3D medical animation. Patient supine. Therapist holds occiput and axis. Subtle rotation at C1-C2 level. Joint highlighted amber. Rotation arc arrows. 8-second loop.", videoSrc:V("osteo-cervical-mob-c1-c2") },

  { id:"osteo-cervical-mob-c2-c7", name:"Mid-Lower Cervical Mobilization C2-C7", region:"Cervical", techniqueType:"joint-mobilization", patientPosition:"Supine", therapistPosition:"At head of table", description:"Segmental cervical AP glide for mid-lower cervical stiffness — Maitland grades II-IV.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts specific vertebra. Applies AP glide. Facet joint highlighted amber. Mobilization arrows. 8-second loop.", videoSrc:V("osteo-cervical-mob-c2-c7") },

  { id:"osteo-thoracic-mob-t1-t4", name:"Upper Thoracic Mobilization T1-T4", region:"Thoracic", techniqueType:"joint-mobilization", patientPosition:"Prone", therapistPosition:"Beside table", description:"PA central mobilization of upper thoracic segments for stiffness and postural correction.", animationPrompt:"3D medical animation. Patient prone, therapist stands beside. Both thumbs on spinous process T1-T4. Applies PA force. Vertebrae highlighted amber. Mobilization arrows. 8-second loop.", videoSrc:V("osteo-thoracic-mob-t1-t4") },

  { id:"osteo-thoracic-mob-t4-t8", name:"Mid-Thoracic Mobilization T4-T8", region:"Thoracic", techniqueType:"joint-mobilization", patientPosition:"Prone", therapistPosition:"Beside table", description:"PA mobilization of mid-thoracic segments — most common area of thoracic dysfunction.", animationPrompt:"3D medical animation. Patient prone, therapist applies bilateral PA thumbs T4-T8. Mid-thoracic segments highlighted. PA arrows. 8-second loop.", videoSrc:V("osteo-thoracic-mob-t4-t8") },

  { id:"osteo-thoracic-mob-t8-t12", name:"Lower Thoracic Mobilization T8-T12", region:"Thoracic", techniqueType:"joint-mobilization", patientPosition:"Prone", therapistPosition:"Beside table", description:"Lower thoracic PA mobilization — addresses thoracolumbar junction dysfunction.", animationPrompt:"3D medical animation. Patient prone, therapist applies PA at T8-T12. Lower thoracic highlighted amber. 8-second loop.", videoSrc:V("osteo-thoracic-mob-t8-t12") },

  { id:"osteo-lumbar-mob-l1-l5", name:"Lumbar Segmental Mobilization L1-L5", region:"Lumbar", techniqueType:"joint-mobilization", patientPosition:"Prone", therapistPosition:"Beside table", description:"Lumbar central PA mobilization — grades II-IV for LBP and stiffness.", animationPrompt:"3D medical animation. Patient prone, therapist applies PA central lumbar force. Lumbar facets highlighted amber. Mobilization force arrows. 8-second loop.", videoSrc:V("osteo-lumbar-mob-l1-l5") },

  { id:"osteo-sacroiliac-mob", name:"Sacroiliac Joint Mobilization", region:"Pelvis", techniqueType:"joint-mobilization", patientPosition:"Side-lying", therapistPosition:"Behind patient", description:"SI joint gapping mobilization for pelvic girdle pain and SIJ dysfunction.", animationPrompt:"3D medical animation. Patient side-lying, therapist behind. Gapping force applied to sacrum. SIJ highlighted amber. Gap arrows. 8-second loop.", videoSrc:V("osteo-sacroiliac-mob") },

  { id:"osteo-shoulder-glenohumeral-mob", name:"Glenohumeral Joint Mobilization", region:"Shoulder", techniqueType:"joint-mobilization", patientPosition:"Supine", therapistPosition:"Beside table", description:"Inferior-posterior glenohumeral glide for frozen shoulder and impingement.", animationPrompt:"3D medical animation. Patient supine, arm at 45° abduction. Therapist applies inferior-posterior glide to humeral head. GH joint highlighted. Glide arrows. 8-second loop.", videoSrc:V("osteo-shoulder-glenohumeral-mob") },

  { id:"osteo-shoulder-acromioclavicular-mob", name:"AC Joint Mobilization", region:"Shoulder", techniqueType:"joint-mobilization", patientPosition:"Seated", therapistPosition:"Behind patient", description:"Acromioclavicular joint AP mobilization for shoulder pain and limited overhead function.", animationPrompt:"3D medical animation. Patient seated, therapist behind. Thumb contacts AC joint. Gentle AP mobilization. AC joint highlighted amber. 8-second loop.", videoSrc:V("osteo-shoulder-acromioclavicular-mob") },

  { id:"osteo-elbow-radiohumeral-mob", name:"Radiohumeral Mobilization", region:"Elbow", techniqueType:"joint-mobilization", patientPosition:"Supine", therapistPosition:"Beside table", description:"Radiohumeral joint mobilization for lateral elbow pain and elbow stiffness.", animationPrompt:"3D medical animation. Patient supine, elbow at 90°. Therapist applies lateral distraction to radial head. Joint highlighted amber. Distraction arrows. 8-second loop.", videoSrc:V("osteo-elbow-radiohumeral-mob") },

  { id:"osteo-elbow-proximal-radioulnar-mob", name:"Proximal Radioulnar Mobilization", region:"Elbow", techniqueType:"joint-mobilization", patientPosition:"Supine", therapistPosition:"Beside table", description:"Proximal radioulnar joint AP mobilization for forearm rotation restriction.", animationPrompt:"3D medical animation. Patient supine, elbow supported. Therapist contacts radial head, applies AP/PA glide. Radioulnar joint highlighted. Glide arrows. 8-second loop.", videoSrc:V("osteo-elbow-proximal-radioulnar-mob") },

  { id:"osteo-wrist-radiocarpal-mob", name:"Radiocarpal Mobilization", region:"Wrist", techniqueType:"joint-mobilization", patientPosition:"Seated", therapistPosition:"Opposite patient", description:"Radiocarpal glide mobilization for wrist stiffness post-fracture or immobilization.", animationPrompt:"3D medical animation. Patient seated, forearm supported. Therapist applies carpal glides: anterior, posterior, radial, ulnar. Radiocarpal joint highlighted. Glide arrows. 8-second loop.", videoSrc:V("osteo-wrist-radiocarpal-mob") },

  { id:"osteo-hip-mob-anterior-glide", name:"Hip Anterior Glide Mobilization", region:"Hip", techniqueType:"joint-mobilization", patientPosition:"Prone", therapistPosition:"Beside table", description:"Anterior glide of femoral head for hip extension and ER restriction.", animationPrompt:"3D medical animation. Patient prone, hip in neutral. Therapist applies anterior force to posterior femur. Hip joint highlighted amber. Anterior glide arrows. 8-second loop.", videoSrc:V("osteo-hip-mob-anterior-glide") },

  { id:"osteo-hip-mob-posterior-glide", name:"Hip Posterior Glide Mobilization", region:"Hip", techniqueType:"joint-mobilization", patientPosition:"Supine", therapistPosition:"Beside table", description:"Posterior femoral head glide for hip flexion restriction and FAI.", animationPrompt:"3D medical animation. Patient supine, hip at 90°. Therapist applies posterior force to anterior femur. Hip joint highlighted. Posterior glide arrows. 8-second loop.", videoSrc:V("osteo-hip-mob-posterior-glide") },

  { id:"osteo-hip-mob-lateral-distraction", name:"Hip Lateral Distraction", region:"Hip", techniqueType:"joint-mobilization", patientPosition:"Supine", therapistPosition:"Beside table", description:"Lateral hip joint distraction — decompresses joint space for OA and pain relief.", animationPrompt:"3D medical animation. Patient supine, band around proximal thigh providing lateral traction. Therapist assists ROM. Joint space opens. Distraction arrows. 8-second loop.", videoSrc:V("osteo-hip-mob-lateral-distraction") },

  { id:"osteo-knee-tibiofemoral-mob", name:"Tibiofemoral Mobilization", region:"Knee", techniqueType:"joint-mobilization", patientPosition:"Supine", therapistPosition:"At foot of table", description:"Anterior-posterior tibial glide for knee flexion/extension restrictions.", animationPrompt:"3D medical animation. Patient supine, knee slightly flexed. Therapist contacts proximal tibia, applies AP glide. Tibiofemoral joint highlighted. Glide arrows. 8-second loop.", videoSrc:V("osteo-knee-tibiofemoral-mob") },

  { id:"osteo-knee-patellofemoral-mob", name:"Patellofemoral Mobilization", region:"Knee", techniqueType:"joint-mobilization", patientPosition:"Supine", therapistPosition:"Beside table", description:"Patellar glide in 4 directions — medial, lateral, superior, inferior for PFPS and post-surgical stiffness.", animationPrompt:"3D medical animation. Patient supine, knee relaxed. Therapist moves patella in 4 directions. Patella highlighted amber. Glide arrows in 4 directions. 8-second loop.", videoSrc:V("osteo-knee-patellofemoral-mob") },

  { id:"osteo-ankle-talocrural-mob", name:"Talocrural Mobilization", region:"Ankle", techniqueType:"joint-mobilization", patientPosition:"Supine", therapistPosition:"At foot of table", description:"Anterior talar glide for ankle dorsiflexion restriction.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts posterior talus, applies anterior talar glide. Talocrural joint highlighted amber. Anterior glide arrows. 8-second loop.", videoSrc:V("osteo-ankle-talocrural-mob") },

  { id:"osteo-ankle-subtalar-mob", name:"Subtalar Mobilization", region:"Ankle", techniqueType:"joint-mobilization", patientPosition:"Supine", therapistPosition:"At foot of table", description:"Subtalar medial-lateral glide for inversion/eversion restriction.", animationPrompt:"3D medical animation. Patient supine, foot supported. Therapist rocks calcaneus medially and laterally. Subtalar joint highlighted. Glide arrows. 8-second loop.", videoSrc:V("osteo-ankle-subtalar-mob") },

  { id:"osteo-first-metatarsophalangeal-mob", name:"1st MTP Mobilization", region:"Foot", techniqueType:"joint-mobilization", patientPosition:"Supine", therapistPosition:"At foot of table", description:"1st MTP distraction and glide for hallux limitus and gout.", animationPrompt:"3D medical animation. Patient supine. Therapist grasps proximal phalanx of hallux, applies distraction and extension. 1st MTP highlighted amber. Distraction arrows. 8-second loop.", videoSrc:V("osteo-first-metatarsophalangeal-mob") },

  { id:"osteo-rib-mob-anterior", name:"Anterior Rib Mobilization", region:"Thorax", techniqueType:"joint-mobilization", patientPosition:"Supine", therapistPosition:"Beside table", description:"Anterior rib mobilization for rib stiffness, breathing restriction, and chest wall pain.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts anterior rib angle, applies PA glide. Rib joint highlighted amber. Mobilization arrows. 8-second loop.", videoSrc:V("osteo-rib-mob-anterior") },

  { id:"osteo-rib-mob-posterior", name:"Posterior Rib Mobilization", region:"Thorax", techniqueType:"joint-mobilization", patientPosition:"Prone", therapistPosition:"Beside table", description:"Posterior rib mobilization at costotransverse joint — PA glide for rib dysfunction.", animationPrompt:"3D medical animation. Patient prone. Therapist contacts posterior rib angle PA. Costotransverse joint highlighted amber. PA arrows. 8-second loop.", videoSrc:V("osteo-rib-mob-posterior") },

  { id:"osteo-clavicle-sternoclavicular-mob", name:"Sternoclavicular Joint Mobilization", region:"Shoulder", techniqueType:"joint-mobilization", patientPosition:"Supine", therapistPosition:"Beside table", description:"SC joint AP/PA glide for clavicle restriction and shoulder girdle dysfunction.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts medial clavicle at SC joint. Applies anterior-posterior glide. SC joint highlighted. Glide arrows. 8-second loop.", videoSrc:V("osteo-clavicle-sternoclavicular-mob") },

  { id:"osteo-tmj-mob", name:"TMJ Mobilization", region:"Jaw", techniqueType:"joint-mobilization", patientPosition:"Supine", therapistPosition:"At head of table", description:"Temporomandibular joint glide and distraction for TMD and jaw restriction.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts mandibular condyle, applies gentle inferior-anterior distraction. TMJ highlighted amber. 8-second loop.", videoSrc:V("osteo-tmj-mob") },

  // ═══════════════════════════════════════════════════════════════════════════
  // HVLA — 20 techniques
  // ═══════════════════════════════════════════════════════════════════════════

  { id:"osteo-hvla-cervical-rotation", name:"Cervical HVLA — Rotation", region:"Cervical", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Supine", therapistPosition:"At head of table", description:"High-velocity low-amplitude cervical rotation thrust for C2-C7 rotational restriction.", animationPrompt:"3D medical animation. Patient supine, therapist at head. Therapist localizes to restricted segment, applies short-amplitude rotation thrust. Cervical facet highlighted amber. Thrust arrow. 6-second loop.", videoSrc:V("osteo-hvla-cervical-rotation"), tip:"Contraindicated: VBI, RA, severe osteoporosis, arterial pathology." },

  { id:"osteo-hvla-cervical-flexion-rotation", name:"Cervical HVLA — Flexion-Rotation", region:"Cervical", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Supine", therapistPosition:"At head of table", description:"Flexion-rotation thrust targeting C1-C2 for upper cervical rotation restriction and cervicogenic headache.", animationPrompt:"3D medical animation. Patient supine, neck fully flexed, then rotated. Therapist applies high-velocity rotation thrust at C1-C2. Upper cervical highlighted. Thrust arc arrow. 6-second loop.", videoSrc:V("osteo-hvla-cervical-flexion-rotation") },

  { id:"osteo-hvla-upper-thoracic", name:"Upper Thoracic HVLA — Dog Technique", region:"Thoracic", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Supine", therapistPosition:"Beside table", description:"Supine upper thoracic HVLA manipulation using crossed-arm contact (dog technique).", animationPrompt:"3D medical animation. Patient supine, arms crossed. Therapist contacts T1-T4 with thenar eminence. Delivers AP thrust. Upper thoracic highlighted amber. Thrust arrows. 6-second loop.", videoSrc:V("osteo-hvla-upper-thoracic") },

  { id:"osteo-hvla-mid-thoracic-sitting", name:"Mid-Thoracic HVLA — Seated", region:"Thoracic", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Seated", therapistPosition:"Behind patient", description:"Seated mid-thoracic HVLA with patient's arms crossed — therapist reinforces from behind.", animationPrompt:"3D medical animation. Patient seated, arms crossed. Therapist behind, knee against thoracic level. Applies anterior-superior thrust. Mid-thoracic highlighted. Thrust arrows. 6-second loop.", videoSrc:V("osteo-hvla-mid-thoracic-sitting") },

  { id:"osteo-hvla-mid-thoracic-supine", name:"Mid-Thoracic HVLA — Supine", region:"Thoracic", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Supine", therapistPosition:"Beside table", description:"Supine mid-thoracic manipulation — therapist's thenar over spinous process delivers AP thrust.", animationPrompt:"3D medical animation. Patient supine over therapist's thenar contact. PA thrust applied. Mid-thoracic highlighted amber. Thrust arrows. 6-second loop.", videoSrc:V("osteo-hvla-mid-thoracic-supine") },

  { id:"osteo-hvla-lower-thoracic", name:"Lower Thoracic HVLA", region:"Thoracic", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Prone", therapistPosition:"Beside table", description:"Prone lower thoracic HVLA at T9-T12 — addresses thoracolumbar junction restriction.", animationPrompt:"3D medical animation. Patient prone. Therapist applies bilateral thumb PA thrust at lower thoracic. T9-T12 highlighted amber. Thrust arrows. 6-second loop.", videoSrc:V("osteo-hvla-lower-thoracic") },

  { id:"osteo-hvla-lumbar-sidebending", name:"Lumbar HVLA — Side-Bend Technique", region:"Lumbar", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Side-lying", therapistPosition:"Beside table", description:"Lumbar rotational HVLA in side-lying using flexion gap technique — grade V mobilization.", animationPrompt:"3D medical animation. Patient side-lying, lumbar locked in flexion. Therapist rotates thorax one way, pelvis opposite. High-velocity thrust delivered. Lumbar facet highlighted. Thrust arrows. 6-second loop.", videoSrc:V("osteo-hvla-lumbar-sidebending"), tip:"Ensure appropriate locking technique before thrust delivery." },

  { id:"osteo-hvla-lumbar-rotation", name:"Lumbar HVLA — Rotation Thrust", region:"Lumbar", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Side-lying", therapistPosition:"Beside table", description:"Lumbar rotational thrust for facet dysfunction and acute LBP — bilateral control.", animationPrompt:"3D medical animation. Patient side-lying. Therapist applies rotational thrust to lumbar. Lumbar segment highlighted. Rotation thrust arrow. 6-second loop.", videoSrc:V("osteo-hvla-lumbar-rotation") },

  { id:"osteo-hvla-sacroiliac-posterior", name:"Posterior SIJ HVLA", region:"Pelvis", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Side-lying", therapistPosition:"Beside table", description:"Posterior iliac HVLA for posteriorly rotated ilium dysfunction.", animationPrompt:"3D medical animation. Patient side-lying, top hip flexed. Therapist contacts PSIS, delivers anterior thrust. SIJ highlighted amber. Thrust arrows. 6-second loop.", videoSrc:V("osteo-hvla-sacroiliac-posterior") },

  { id:"osteo-hvla-sacroiliac-anterior", name:"Anterior SIJ HVLA", region:"Pelvis", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Supine", therapistPosition:"Beside table", description:"Anterior iliac HVLA for anteriorly rotated ilium — drops the ASIS.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts ASIS, applies posterior thrust. SIJ highlighted amber. Posterior thrust arrows. 6-second loop.", videoSrc:V("osteo-hvla-sacroiliac-anterior") },

  { id:"osteo-hvla-sacrum-shear", name:"Sacral Shear HVLA", region:"Pelvis", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Prone", therapistPosition:"Beside table", description:"Sacral shear manipulation for sacral torsion and unilateral sacral flexion dysfunction.", animationPrompt:"3D medical animation. Patient prone. Therapist applies shearing force to sacrum. Sacrum highlighted amber. Shear thrust arrows. 6-second loop.", videoSrc:V("osteo-hvla-sacrum-shear") },

  { id:"osteo-hvla-pubic-symphysis", name:"Pubic Symphysis HVLA", region:"Pelvis", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Supine", therapistPosition:"Beside table", description:"Pubic symphysis gap or compression technique for pelvic girdle pain.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts pubic tubercles bilaterally. Applies compression or distraction thrust. Symphysis highlighted. Thrust arrows. 6-second loop.", videoSrc:V("osteo-hvla-pubic-symphysis") },

  { id:"osteo-hvla-rib-pump-supine", name:"Rib HVLA — Pump Technique Supine", region:"Thorax", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Supine", therapistPosition:"Beside table", description:"Supine rib pump HVLA for exhalation rib dysfunction — opens the intercostal space.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts rib angle anteriorly. Applies quick superior-posterior thrust. Rib highlighted amber. Pump thrust arrows. 6-second loop.", videoSrc:V("osteo-hvla-rib-pump-supine") },

  { id:"osteo-hvla-rib-sitting", name:"Rib HVLA — Seated", region:"Thorax", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Seated", therapistPosition:"Behind patient", description:"Seated rib manipulation for inhalation rib dysfunction — upper ribs 1-3.", animationPrompt:"3D medical animation. Patient seated, arm raised. Therapist contacts first rib from behind. Applies inferolateral thrust. First rib highlighted amber. Thrust arrows. 6-second loop.", videoSrc:V("osteo-hvla-rib-sitting") },

  { id:"osteo-hvla-hip-scouring", name:"Hip HVLA — Scouring Technique", region:"Hip", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Supine", therapistPosition:"At foot of table", description:"Hip scouring manipulation for hip OA and joint restriction — combined flexion-ER thrust.", animationPrompt:"3D medical animation. Patient supine, hip flexed and ER. Therapist applies downward compression + rotational thrust through femur. Hip joint highlighted. Scour arrows. 6-second loop.", videoSrc:V("osteo-hvla-hip-scouring") },

  { id:"osteo-hvla-elbow-lateral-gap", name:"Elbow Lateral Gap HVLA", region:"Elbow", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Supine", therapistPosition:"Beside table", description:"Lateral elbow joint gap thrust for stiffness and lateral epicondylopathy.", animationPrompt:"3D medical animation. Patient supine, elbow semi-flexed. Therapist applies lateral distraction thrust. Elbow joint highlighted amber. Gap thrust arrows. 6-second loop.", videoSrc:V("osteo-hvla-elbow-lateral-gap") },

  { id:"osteo-hvla-wrist-carpal", name:"Wrist Carpal HVLA", region:"Wrist", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Seated", therapistPosition:"Opposite patient", description:"Carpal bone manipulation for wrist stiffness and post-colles fracture.", animationPrompt:"3D medical animation. Patient seated, forearm supported. Therapist grasps specific carpal, delivers precise thrust. Carpal highlighted amber. Thrust arrows. 6-second loop.", videoSrc:V("osteo-hvla-wrist-carpal") },

  { id:"osteo-hvla-ankle-mortise", name:"Ankle Mortise HVLA", region:"Ankle", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Supine", therapistPosition:"At foot of table", description:"Ankle mortise distraction thrust for ankle dorsiflexion restriction and ankle OA.", animationPrompt:"3D medical animation. Patient supine. Therapist grasps heel and forefoot, delivers quick distraction thrust. Ankle mortise highlighted amber. Distraction thrust arrows. 6-second loop.", videoSrc:V("osteo-hvla-ankle-mortise") },

  { id:"osteo-hvla-cuboid-notch", name:"Cuboid Notch HVLA", region:"Foot", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Prone", therapistPosition:"At foot of table", description:"Cuboid manipulation for lateral foot pain and cuboid syndrome.", animationPrompt:"3D medical animation. Patient prone, foot off table. Therapist thumbs on plantar cuboid, applies quick dorsal thrust. Cuboid highlighted amber. Thrust arrows. 6-second loop.", videoSrc:V("osteo-hvla-cuboid-notch") },

  { id:"osteo-hvla-first-rib", name:"First Rib HVLA", region:"Thorax/Cervical", techniqueType:"hvla", isChiropracticDerived:true, patientPosition:"Seated", therapistPosition:"Behind patient", description:"First rib inferior glide thrust for TOS and cerviobrachial pain — one of the most clinically important rib manipulations.", animationPrompt:"3D medical animation. Patient seated. Therapist contacts first rib from above, head in ipsilateral rotation. Applies inferior thrust. First rib highlighted amber. Inferior thrust arrows. 6-second loop.", videoSrc:V("osteo-hvla-first-rib"), tip:"Screen for TOS and brachial plexus involvement before applying." },

  // ═══════════════════════════════════════════════════════════════════════════
  // MUSCLE ENERGY TECHNIQUE — 25 techniques
  // ═══════════════════════════════════════════════════════════════════════════

  { id:"osteo-met-cervical-flexion", name:"Cervical MET — Flexion Restriction", region:"Cervical", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"At head of table", description:"MET for cervical flexion restriction — patient resists extension, therapist takes up slack.", animationPrompt:"3D medical animation. Patient supine, neck at flexion barrier. Patient contracts extension against therapist's resistance. Hold 5s. Therapist takes up new barrier. Cervical muscles highlighted. MET sequence arrows. 8-second loop.", videoSrc:V("osteo-met-cervical-flexion") },

  { id:"osteo-met-cervical-extension", name:"Cervical MET — Extension Restriction", region:"Cervical", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"At head of table", description:"MET for cervical extension restriction — patient resists flexion at extension barrier.", animationPrompt:"3D medical animation. Patient supine, neck at extension barrier. Patient contracts flexion against resistance 5s. Therapist takes up slack. Cervical extensors highlighted. MET arrows. 8-second loop.", videoSrc:V("osteo-met-cervical-extension") },

  { id:"osteo-met-cervical-rotation", name:"Cervical MET — Rotation Restriction", region:"Cervical", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"At head of table", description:"MET for cervical rotation restriction — isometric contraction into restriction, then stretch.", animationPrompt:"3D medical animation. Patient supine, head rotated to restriction. Patient contracts against resistance 5s. Therapist rotates further. Cervical rotators highlighted. MET sequence. 8-second loop.", videoSrc:V("osteo-met-cervical-rotation") },

  { id:"osteo-met-cervical-sidebend", name:"Cervical MET — Side-Bend Restriction", region:"Cervical", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"At head of table", description:"MET for cervical lateral flexion restriction — scalene and upper trap targeting.", animationPrompt:"3D medical animation. Patient supine, neck side-bent to barrier. Patient resists for 5s. Therapist deepens stretch. Lateral cervical muscles highlighted. MET sequence. 8-second loop.", videoSrc:V("osteo-met-cervical-sidebend") },

  { id:"osteo-met-thoracic-rotation", name:"Thoracic MET — Rotation Restriction", region:"Thoracic", techniqueType:"muscle-energy", patientPosition:"Seated", therapistPosition:"Behind patient", description:"Seated thoracic MET for rotational restriction — patient activates rotators then therapist gains range.", animationPrompt:"3D medical animation. Patient seated, thorax rotated to restriction. Patient pushes back against resistance 5s. Therapist gains further rotation. Thoracic rotators highlighted. MET arrows. 8-second loop.", videoSrc:V("osteo-met-thoracic-rotation") },

  { id:"osteo-met-thoracic-extension", name:"Thoracic MET — Extension Restriction", region:"Thoracic", techniqueType:"muscle-energy", patientPosition:"Seated", therapistPosition:"Behind patient", description:"Thoracic extension MET for kyphosis and extension restriction.", animationPrompt:"3D medical animation. Patient seated, thorax at extension barrier. Patient resists flexion 5s. Therapist extends further. Thoracic extensors highlighted. MET sequence. 8-second loop.", videoSrc:V("osteo-met-thoracic-extension") },

  { id:"osteo-met-lumbar-rotation", name:"Lumbar MET — Rotation Restriction", region:"Lumbar", techniqueType:"muscle-energy", patientPosition:"Side-lying", therapistPosition:"Beside table", description:"Side-lying lumbar MET for rotational restriction — highly specific segmental technique.", animationPrompt:"3D medical animation. Patient side-lying, lumbar at rotation barrier. Patient rotates against resistance 5s. Therapist gains more rotation. Lumbar rotators highlighted. MET sequence. 8-second loop.", videoSrc:V("osteo-met-lumbar-rotation") },

  { id:"osteo-met-lumbar-extension", name:"Lumbar MET — Extension Restriction", region:"Lumbar", techniqueType:"muscle-energy", patientPosition:"Prone", therapistPosition:"Beside table", description:"Prone lumbar extension MET for flexion-biased restriction.", animationPrompt:"3D medical animation. Patient prone, hip at extension barrier. Patient flexes against resistance 5s. Therapist gains extension. Lumbar extensors highlighted. MET sequence. 8-second loop.", videoSrc:V("osteo-met-lumbar-extension") },

  { id:"osteo-met-sacroiliac-iliac-anterior", name:"SIJ MET — Anterior Iliac Rotation", region:"Pelvis", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"Beside table", description:"MET for anteriorly rotated ilium — the most common SIJ dysfunction.", animationPrompt:"3D medical animation. Patient supine, hip flexed. Patient resists extension 5s. Therapist pushes ilium posterior. SIJ highlighted amber. MET correction arrows. 8-second loop.", videoSrc:V("osteo-met-sacroiliac-iliac-anterior") },

  { id:"osteo-met-sacroiliac-iliac-posterior", name:"SIJ MET — Posterior Iliac Rotation", region:"Pelvis", techniqueType:"muscle-energy", patientPosition:"Prone", therapistPosition:"Beside table", description:"MET for posteriorly rotated ilium — hip extension contraction followed by anterior correction.", animationPrompt:"3D medical animation. Patient prone, hip extended. Patient resists flexion 5s. Therapist moves ilium anterior. SIJ highlighted. MET arrows. 8-second loop.", videoSrc:V("osteo-met-sacroiliac-iliac-posterior") },

  { id:"osteo-met-piriformis", name:"Piriformis MET", region:"Hip", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"Beside table", description:"MET for piriformis shortening — hip IR contraction followed by ER stretch.", animationPrompt:"3D medical animation. Patient supine, hip in figure-four position. Patient contracts piriformis for 5s. Therapist deepens ER stretch. Piriformis highlighted amber. MET sequence. 8-second loop.", videoSrc:V("osteo-met-piriformis") },

  { id:"osteo-met-psoas", name:"Psoas MET", region:"Hip", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"Beside table", description:"Psoas MET using Thomas test position — hip flexion contraction followed by passive extension.", animationPrompt:"3D medical animation. Patient supine, one hip extended off table. Patient contracts flexion against resistance 5s. Therapist gains extension. Psoas highlighted amber. MET sequence. 8-second loop.", videoSrc:V("osteo-met-psoas") },

  { id:"osteo-met-quadratus-lumborum", name:"Quadratus Lumborum MET", region:"Lumbar", techniqueType:"muscle-energy", patientPosition:"Side-lying", therapistPosition:"Beside table", description:"QL MET for lateral flexion restriction and hip-drop-related LBP.", animationPrompt:"3D medical animation. Patient side-lying, QL at stretch barrier. Patient contracts lateral flexion 5s. Therapist gains further stretch. QL highlighted amber. MET sequence. 8-second loop.", videoSrc:V("osteo-met-quadratus-lumborum") },

  { id:"osteo-met-hamstrings", name:"Hamstrings MET", region:"Hip/Knee", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"Beside table", description:"Supine hamstring MET — PIR (post-isometric relaxation) for hamstring shortening.", animationPrompt:"3D medical animation. Patient supine, SLR to stretch barrier. Patient extends knee against resistance 5s. Therapist gains more SLR. Hamstrings highlighted amber. MET sequence. 8-second loop.", videoSrc:V("osteo-met-hamstrings") },

  { id:"osteo-met-adductors", name:"Adductors MET", region:"Hip", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"Beside table", description:"Adductor MET in abduction — for groin tightness and SIJ related adductor dysfunction.", animationPrompt:"3D medical animation. Patient supine, hip abducted to barrier. Patient adducts against resistance 5s. Therapist gains abduction. Adductors highlighted amber. MET sequence. 8-second loop.", videoSrc:V("osteo-met-adductors") },

  { id:"osteo-met-shoulder-internal-rotation", name:"Shoulder IR MET", region:"Shoulder", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"Beside table", description:"Shoulder IR MET for external rotator shortening — sleeper stretch MET variant.", animationPrompt:"3D medical animation. Patient supine, shoulder at IR barrier. Patient contracts ER against resistance 5s. Therapist gains IR. External rotators highlighted. MET sequence. 8-second loop.", videoSrc:V("osteo-met-shoulder-internal-rotation") },

  { id:"osteo-met-shoulder-external-rotation", name:"Shoulder ER MET", region:"Shoulder", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"Beside table", description:"Shoulder ER MET for internal rotator/subscapularis tightening.", animationPrompt:"3D medical animation. Patient supine, shoulder at ER barrier. Patient contracts IR 5s. Therapist gains ER. Subscapularis highlighted amber. MET sequence. 8-second loop.", videoSrc:V("osteo-met-shoulder-external-rotation") },

  { id:"osteo-met-shoulder-elevation", name:"Shoulder Elevation MET", region:"Shoulder", techniqueType:"muscle-energy", patientPosition:"Seated", therapistPosition:"Behind patient", description:"MET for shoulder girdle elevation restriction — upper trap and levator scapulae.", animationPrompt:"3D medical animation. Patient seated. Therapist at shoulder. Patient elevates shoulder against resistance 5s. Therapist depresses. Upper trap highlighted. MET sequence. 8-second loop.", videoSrc:V("osteo-met-shoulder-elevation") },

  { id:"osteo-met-elbow-flexion", name:"Elbow Flexion MET", region:"Elbow", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"Beside table", description:"Biceps MET for elbow flexion contracture — extension barrier approach.", animationPrompt:"3D medical animation. Patient supine, elbow at extension barrier. Patient flexes against resistance 5s. Therapist gains extension. Biceps highlighted amber. MET sequence. 8-second loop.", videoSrc:V("osteo-met-elbow-flexion") },

  { id:"osteo-met-ankle-plantarflexion", name:"Ankle Plantarflexion MET", region:"Ankle", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"At foot of table", description:"Calf/Achilles MET for ankle plantarflexion restriction.", animationPrompt:"3D medical animation. Patient supine, ankle at DF barrier. Patient plantarflexes against resistance 5s. Therapist gains DF. Calf highlighted amber. MET sequence. 8-second loop.", videoSrc:V("osteo-met-ankle-plantarflexion") },

  { id:"osteo-met-ankle-dorsiflexion", name:"Ankle Dorsiflexion MET", region:"Ankle", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"At foot of table", description:"Tibialis anterior MET for plantarflexion restriction.", animationPrompt:"3D medical animation. Patient supine, ankle at PF barrier. Patient dorsiflexes against resistance 5s. Therapist gains PF. Tibialis anterior highlighted. MET sequence. 8-second loop.", videoSrc:V("osteo-met-ankle-dorsiflexion") },

  { id:"osteo-met-ribs-exhalation", name:"Exhalation Rib MET", region:"Thorax", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"Beside table", description:"MET for exhalation rib dysfunction — intercostal and scalene activation.", animationPrompt:"3D medical animation. Patient supine, restricted rib identified. Patient inhales against resistance at rib. Therapist takes up exhalation restriction. Intercostals highlighted. MET sequence. 8-second loop.", videoSrc:V("osteo-met-ribs-exhalation") },

  { id:"osteo-met-ribs-inhalation", name:"Inhalation Rib MET", region:"Thorax", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"Beside table", description:"MET for inhalation rib dysfunction — serratus and intercostal activation.", animationPrompt:"3D medical animation. Patient supine, restricted rib. Patient exhales against rib resistance. Therapist takes up inhalation restriction. Serratus and intercostals highlighted. MET sequence. 8-second loop.", videoSrc:V("osteo-met-ribs-inhalation") },

  { id:"osteo-met-upper-trap", name:"Upper Trapezius MET", region:"Cervical/Thoracic", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"At head of table", description:"Upper trapezius PIR — lateral cervical flexion barrier with shoulder elevation contraction.", animationPrompt:"3D medical animation. Patient supine, neck side-bent, shoulder depressed to stretch barrier. Patient elevates shoulder against resistance 5s. Upper trap highlighted amber. Therapist gains stretch. MET arrows. 8-second loop.", videoSrc:V("osteo-met-upper-trap") },

  { id:"osteo-met-levator-scapulae", name:"Levator Scapulae MET", region:"Cervical", techniqueType:"muscle-energy", patientPosition:"Supine", therapistPosition:"At head of table", description:"Levator scapulae PIR — neck flexion-rotation combined with scapular depression contraction.", animationPrompt:"3D medical animation. Patient supine, neck in LS stretch position. Patient elevates scapula against resistance 5s. Therapist deepens stretch. Levator scapulae highlighted amber. MET sequence. 8-second loop.", videoSrc:V("osteo-met-levator-scapulae") },

  // ═══════════════════════════════════════════════════════════════════════════
  // MYOFASCIAL RELEASE — 20 techniques
  // ═══════════════════════════════════════════════════════════════════════════

  { id:"osteo-mfr-thoracolumbar-fascia", name:"Thoracolumbar Fascia Release", region:"Lumbar", techniqueType:"myofascial-release", patientPosition:"Prone", therapistPosition:"Beside table", description:"Indirect TLF release — sustained contact until fascial unwinding for LBP and thoracolumbar stiffness.", animationPrompt:"3D medical animation. Patient prone. Therapist places both hands on TLF. Sustained gentle contact. Fascial layer highlighted amber, shows subtle unwinding motion. Release arrows. 10-second loop.", videoSrc:V("osteo-mfr-thoracolumbar-fascia") },

  { id:"osteo-mfr-cervical-fascia", name:"Cervical Fascia Release", region:"Cervical", techniqueType:"myofascial-release", patientPosition:"Supine", therapistPosition:"At head of table", description:"Indirect cervical fascial unwinding for neck pain, headache, and postural correction.", animationPrompt:"3D medical animation. Patient supine. Therapist cradles cervical spine with both hands. Subtle fascial unwinding motion. Cervical fascia highlighted amber. Release arrows. 10-second loop.", videoSrc:V("osteo-mfr-cervical-fascia") },

  { id:"osteo-mfr-suboccipital", name:"Suboccipital Myofascial Release", region:"Cervical", techniqueType:"myofascial-release", patientPosition:"Supine", therapistPosition:"At head of table", description:"Direct suboccipital MFR — bilateral finger contact under occiput with sustained pressure.", animationPrompt:"3D medical animation. Patient supine. Therapist finger pads under occiput. Sustained pressure with slight inferior traction. Suboccipitals highlighted amber. Release arrows. 10-second loop.", videoSrc:V("osteo-mfr-suboccipital") },

  { id:"osteo-mfr-diaphragm", name:"Diaphragm Release", region:"Thorax/Abdomen", techniqueType:"myofascial-release", patientPosition:"Supine", therapistPosition:"Beside table", description:"Diaphragm MFR — hands under costal margins, synchronizing with respiratory rhythm.", animationPrompt:"3D medical animation. Patient supine. Therapist hands under lower ribs at diaphragm attachment. Follows breathing. Diaphragm highlighted amber. Respiratory synchronization arrows. 10-second loop.", videoSrc:V("osteo-mfr-diaphragm") },

  { id:"osteo-mfr-pelvic-floor", name:"Pelvic Floor Myofascial Release", region:"Pelvis", techniqueType:"myofascial-release", patientPosition:"Supine", therapistPosition:"Beside table", description:"External pelvic floor MFR — indirect technique targeting perineal and pelvic floor fascia.", animationPrompt:"3D medical animation. Patient supine, knees bent. Therapist contacts external pelvic floor points bilaterally. Sustained gentle pressure. Pelvic floor highlighted amber. Release arrows. 10-second loop.", videoSrc:V("osteo-mfr-pelvic-floor") },

  { id:"osteo-mfr-iliotibial-band", name:"IT Band Myofascial Release", region:"Knee/Hip", techniqueType:"myofascial-release", patientPosition:"Side-lying", therapistPosition:"Beside table", description:"Direct IT band MFR with forearm or elbow contact — for lateral knee pain and runner's knee.", animationPrompt:"3D medical animation. Patient side-lying. Therapist forearm contacts lateral thigh IT band. Slow stroke proximal to distal. IT band highlighted amber. Direct pressure arrows. 10-second loop.", videoSrc:V("osteo-mfr-iliotibial-band") },

  { id:"osteo-mfr-psoas-release", name:"Psoas Myofascial Release", region:"Hip", techniqueType:"myofascial-release", patientPosition:"Supine", therapistPosition:"Beside table", description:"Indirect psoas MFR — deep abdominal contact with sustained pressure for psoas shortening.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts abdomen lateral to rectus at L1 level. Slow deep sink. Psoas highlighted amber. Indirect release arrows. 10-second loop.", videoSrc:V("osteo-mfr-psoas-release") },

  { id:"osteo-mfr-piriformis-release", name:"Piriformis Myofascial Release", region:"Hip", techniqueType:"myofascial-release", patientPosition:"Side-lying", therapistPosition:"Beside table", description:"Direct piriformis MFR for sciatica and piriformis syndrome.", animationPrompt:"3D medical animation. Patient side-lying. Therapist thumb or elbow contacts piriformis in glute. Sustained direct pressure. Piriformis highlighted amber. Release arrows. 10-second loop.", videoSrc:V("osteo-mfr-piriformis-release") },

  { id:"osteo-mfr-quadratus-lumborum", name:"QL Myofascial Release", region:"Lumbar", techniqueType:"myofascial-release", patientPosition:"Side-lying", therapistPosition:"Beside table", description:"QL direct MFR for lateral lumbar pain, hip drop, and scoliosis.", animationPrompt:"3D medical animation. Patient side-lying, QL accessible. Therapist forearm contacts QL from iliac crest to 12th rib. Sustained pressure. QL highlighted amber. Direct release arrows. 10-second loop.", videoSrc:V("osteo-mfr-quadratus-lumborum") },

  { id:"osteo-mfr-upper-trapezius", name:"Upper Trapezius MFR", region:"Cervical/Thoracic", techniqueType:"myofascial-release", patientPosition:"Supine", therapistPosition:"At head of table", description:"Upper trapezius direct MFR — sustained pincer or flat contact for tension headaches and neck pain.", animationPrompt:"3D medical animation. Patient supine. Therapist pinches upper trap between thumb and fingers. Sustained direct pressure. Upper trap highlighted amber. Release arrows. 10-second loop.", videoSrc:V("osteo-mfr-upper-trapezius") },

  { id:"osteo-mfr-sternocleidomastoid", name:"SCM Myofascial Release", region:"Cervical", techniqueType:"myofascial-release", patientPosition:"Supine", therapistPosition:"At head of table", description:"SCM MFR using gentle pincer technique — for cervicogenic headache and torticollis.", animationPrompt:"3D medical animation. Patient supine, head slightly rotated. Therapist gently grasps SCM between finger and thumb. Sustained hold. SCM highlighted amber. Release arrows. 10-second loop.", videoSrc:V("osteo-mfr-sternocleidomastoid") },

  { id:"osteo-mfr-scalenes", name:"Scalene Myofascial Release", region:"Cervical", techniqueType:"myofascial-release", patientPosition:"Supine", therapistPosition:"At head of table", description:"Scalene MFR for TOS, cervical stiffness, and breathing dysfunction.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts scalene muscles between SCM and trapezius. Gentle direct pressure. Scalenes highlighted amber. Release arrows. 10-second loop.", videoSrc:V("osteo-mfr-scalenes") },

  { id:"osteo-mfr-anterior-shoulder", name:"Anterior Shoulder MFR", region:"Shoulder", techniqueType:"myofascial-release", patientPosition:"Supine", therapistPosition:"Beside table", description:"Anterior shoulder/pec minor MFR for rounded shoulder posture and impingement.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts anterior shoulder and pec minor. Sustained pressure with arm movement. Pec minor highlighted amber. Release arrows. 10-second loop.", videoSrc:V("osteo-mfr-anterior-shoulder") },

  { id:"osteo-mfr-posterior-shoulder", name:"Posterior Shoulder MFR", region:"Shoulder", techniqueType:"myofascial-release", patientPosition:"Side-lying", therapistPosition:"Beside table", description:"Posterior shoulder capsule and rotator cuff MFR for frozen shoulder and GIRD.", animationPrompt:"3D medical animation. Patient side-lying. Therapist contacts posterior shoulder rotator cuff. Sustained direct pressure. Posterior shoulder highlighted amber. Release arrows. 10-second loop.", videoSrc:V("osteo-mfr-posterior-shoulder") },

  { id:"osteo-mfr-lateral-thigh", name:"Lateral Thigh MFR", region:"Knee/Hip", techniqueType:"myofascial-release", patientPosition:"Side-lying", therapistPosition:"Beside table", description:"Lateral thigh direct MFR targeting TFL and IT band for lateral knee and hip pain.", animationPrompt:"3D medical animation. Patient side-lying. Therapist forearm strokes lateral thigh from hip to knee. TFL and IT band highlighted amber. Stroke arrows. 10-second loop.", videoSrc:V("osteo-mfr-lateral-thigh") },

  { id:"osteo-mfr-medial-knee", name:"Medial Knee MFR", region:"Knee", techniqueType:"myofascial-release", patientPosition:"Supine", therapistPosition:"Beside table", description:"Medial knee retinaculum MFR for medial knee pain and pes anserinus syndrome.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts medial knee retinaculum. Sustained direct pressure with knee movement. Medial structures highlighted amber. Release arrows. 10-second loop.", videoSrc:V("osteo-mfr-medial-knee") },

  { id:"osteo-mfr-plantar-fascia", name:"Plantar Fascia MFR", region:"Foot", techniqueType:"myofascial-release", patientPosition:"Prone", therapistPosition:"At foot of table", description:"Plantar fascia direct MFR with thumb contact — for plantar fasciitis and foot stiffness.", animationPrompt:"3D medical animation. Patient prone, foot off table. Therapist thumbs contact plantar fascia. Slow deep stroke heel to metatarsals. Plantar fascia highlighted amber. Stroke arrows. 10-second loop.", videoSrc:V("osteo-mfr-plantar-fascia") },

  { id:"osteo-mfr-forearm-flexors", name:"Forearm Flexor MFR", region:"Elbow/Wrist", techniqueType:"myofascial-release", patientPosition:"Supine", therapistPosition:"Beside table", description:"Forearm flexor MFR for golfer's elbow and wrist flexor tightness.", animationPrompt:"3D medical animation. Patient supine, arm extended. Therapist strokes forearm flexors from elbow to wrist. Flexors highlighted amber. Stroke arrows. 10-second loop.", videoSrc:V("osteo-mfr-forearm-flexors") },

  { id:"osteo-mfr-forearm-extensors", name:"Forearm Extensor MFR", region:"Elbow/Wrist", techniqueType:"myofascial-release", patientPosition:"Supine", therapistPosition:"Beside table", description:"Forearm extensor MFR for tennis elbow and wrist extensor tightness.", animationPrompt:"3D medical animation. Patient supine, arm extended palm down. Therapist strokes forearm extensors elbow to wrist. Extensors highlighted amber. Stroke arrows. 10-second loop.", videoSrc:V("osteo-mfr-forearm-extensors") },

  { id:"osteo-mfr-rib-intercostals", name:"Intercostal MFR", region:"Thorax", techniqueType:"myofascial-release", patientPosition:"Side-lying", therapistPosition:"Beside table", description:"Intercostal space MFR for rib stiffness, post-fracture pain, and breathing restriction.", animationPrompt:"3D medical animation. Patient side-lying. Therapist fingers slide between rib spaces. Sustained intercostal pressure. Intercostals highlighted amber. Release arrows. 10-second loop.", videoSrc:V("osteo-mfr-rib-intercostals") },

  // ═══════════════════════════════════════════════════════════════════════════
  // VISCERAL OSTEOPATHY — 15 techniques
  // ═══════════════════════════════════════════════════════════════════════════

  { id:"osteo-visceral-liver-mob", name:"Liver Mobilization", region:"Abdomen", techniqueType:"visceral", patientPosition:"Supine", therapistPosition:"Beside table", description:"Visceral liver mobilization following hepatic ligament lines — for right upper quadrant restriction.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts right subcostal region. Gently moves liver through its physiological motion. Liver highlighted amber. Mobilization arrows. 10-second loop.", videoSrc:V("osteo-visceral-liver-mob") },

  { id:"osteo-visceral-stomach-mob", name:"Stomach Mobilization", region:"Abdomen", techniqueType:"visceral", patientPosition:"Supine", therapistPosition:"Beside table", description:"Gastric mobilization for GERD, epigastric pain, and gastric ptosis.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts epigastric region. Gentle rocking and lifting motion. Stomach highlighted amber. Visceral mobilization arrows. 10-second loop.", videoSrc:V("osteo-visceral-stomach-mob") },

  { id:"osteo-visceral-colon-mob", name:"Colon Mobilization", region:"Abdomen", techniqueType:"visceral", patientPosition:"Supine", therapistPosition:"Beside table", description:"Visceral colon mobilization following ascending-transverse-descending pattern for IBS and constipation.", animationPrompt:"3D medical animation. Patient supine. Therapist follows colon pathway: ascending, transverse, descending. Colon highlighted amber. Peristaltic mobilization arrows. 10-second loop.", videoSrc:V("osteo-visceral-colon-mob") },

  { id:"osteo-visceral-small-intestine-mob", name:"Small Intestine Mobilization", region:"Abdomen", techniqueType:"visceral", patientPosition:"Supine", therapistPosition:"Beside table", description:"Small intestine visceral mobilization for adhesions, bloating, and central abdominal restriction.", animationPrompt:"3D medical animation. Patient supine. Therapist circles hands around periumbilical region mobilizing small bowel. Small intestine highlighted amber. Circular mobilization arrows. 10-second loop.", videoSrc:V("osteo-visceral-small-intestine-mob") },

  { id:"osteo-visceral-kidney-ptosis", name:"Kidney Ptosis Technique", region:"Retroperitoneum", techniqueType:"visceral", patientPosition:"Supine", therapistPosition:"Beside table", description:"Kidney lift and repositioning for renal ptosis contributing to lumbar and flank pain.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts posterolateral flank, lifts kidney superiorly. Kidney highlighted amber. Lift and repositioning arrows. 10-second loop.", videoSrc:V("osteo-visceral-kidney-ptosis") },

  { id:"osteo-visceral-bladder-mob", name:"Bladder Mobilization", region:"Pelvis", techniqueType:"visceral", patientPosition:"Supine", therapistPosition:"Beside table", description:"Bladder visceral mobilization for urinary urgency, pelvic pain, and bladder ptosis.", animationPrompt:"3D medical animation. Patient supine, knees bent. Therapist contacts suprapubic region. Gently moves bladder superiorly. Bladder highlighted amber. Superior lift arrows. 10-second loop.", videoSrc:V("osteo-visceral-bladder-mob") },

  { id:"osteo-visceral-uterine-mob", name:"Uterine Mobilization", region:"Pelvis", techniqueType:"visceral", patientPosition:"Supine", therapistPosition:"Beside table", description:"Uterine mobilization for dysmenorrhea, pelvic pain, and uterine retroversion.", animationPrompt:"3D medical animation. Patient supine, knees bent. Therapist contacts anterior uterus externally. Gentle rocking mobilization. Uterus highlighted amber. Mobilization arrows. 10-second loop.", videoSrc:V("osteo-visceral-uterine-mob") },

  { id:"osteo-visceral-sigmoid-mob", name:"Sigmoid Colon Mobilization", region:"Abdomen", techniqueType:"visceral", patientPosition:"Supine", therapistPosition:"Beside table", description:"Sigmoid mobilization for left lower quadrant pain, constipation, and diverticular-related restriction.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts left lower quadrant sigmoid. Gentle S-shaped mobilization. Sigmoid highlighted amber. S-curve arrows. 10-second loop.", videoSrc:V("osteo-visceral-sigmoid-mob") },

  { id:"osteo-visceral-cecum-mob", name:"Cecum Mobilization", region:"Abdomen", techniqueType:"visceral", patientPosition:"Supine", therapistPosition:"Beside table", description:"Cecal mobilization for right lower quadrant tightness and ileocecal region restriction.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts RLQ cecal region. Circular mobilization. Cecum highlighted amber. Mobilization arrows. 10-second loop.", videoSrc:V("osteo-visceral-cecum-mob") },

  { id:"osteo-visceral-diaphragm-dome", name:"Diaphragm Dome Release", region:"Thorax/Abdomen", techniqueType:"visceral", patientPosition:"Supine", therapistPosition:"Beside table", description:"Diaphragm dome lift technique — restores respiratory mobility and relieves hepatic and cardiac restrictions.", animationPrompt:"3D medical animation. Patient supine. Therapist slides hands under costal margins bilaterally. Gentle domed lift of diaphragm. Diaphragm highlighted amber. Dome lift arrows. 10-second loop.", videoSrc:V("osteo-visceral-diaphragm-dome") },

  { id:"osteo-visceral-hiatal-hernia", name:"Hiatal Hernia Technique", region:"Abdomen", techniqueType:"visceral", patientPosition:"Supine", therapistPosition:"Beside table", description:"Hiatal hernia manual reduction technique for GERD and epigastric pain.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts left epigastric area. Lifts and pushes stomach inferior to reduce herniation. Esophageal hiatus highlighted amber. Reduction arrows. 10-second loop.", videoSrc:V("osteo-visceral-hiatal-hernia") },

  { id:"osteo-visceral-ileocecal-valve", name:"Ileocecal Valve Technique", region:"Abdomen", techniqueType:"visceral", patientPosition:"Supine", therapistPosition:"Beside table", description:"ICV normalization technique for IBS, food sensitivities, and systemic toxicity symptoms.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts McBurney's point area. Applies specific ICV open or close technique. ICV highlighted amber. Technique arrows. 10-second loop.", videoSrc:V("osteo-visceral-ileocecal-valve") },

  { id:"osteo-visceral-portal-liver", name:"Portal Liver Pump", region:"Abdomen", techniqueType:"visceral", patientPosition:"Supine", therapistPosition:"Beside table", description:"Hepatic pump technique to improve portal circulation and lymphatic drainage.", animationPrompt:"3D medical animation. Patient supine. Therapist rhythmically compresses right upper quadrant. Portal circulation arrows visible. Liver highlighted amber. Pump rhythm. 10-second loop.", videoSrc:V("osteo-visceral-portal-liver") },

  { id:"osteo-visceral-gallbladder", name:"Gallbladder Mobilization", region:"Abdomen", techniqueType:"visceral", patientPosition:"Supine", therapistPosition:"Beside table", description:"Gallbladder visceral technique for biliary stasis and right shoulder referred pain.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts gallbladder fossa under right costal margin. Gentle rocking motion. Gallbladder highlighted amber. Mobilization arrows. 10-second loop.", videoSrc:V("osteo-visceral-gallbladder") },

  { id:"osteo-visceral-spleen", name:"Spleen Mobilization", region:"Abdomen", techniqueType:"visceral", patientPosition:"Supine", therapistPosition:"Beside table", description:"Spleen visceral mobilization for left upper quadrant tightness and immune support.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts left subcostal region. Gentle anterior-medial spleen mobilization. Spleen highlighted amber. Mobilization arrows. 10-second loop.", videoSrc:V("osteo-visceral-spleen") },

  // ═══════════════════════════════════════════════════════════════════════════
  // CRANIAL OSTEOPATHY — 15 techniques
  // ═══════════════════════════════════════════════════════════════════════════

  { id:"osteo-cranial-frontoparietal", name:"Frontoparietal Hold", region:"Cranium", techniqueType:"cranial", patientPosition:"Supine", therapistPosition:"At head of table", description:"Palpation and correction of frontal-parietal suture restriction through CRI synchronization.", animationPrompt:"3D medical animation. Patient supine. Therapist one hand on frontal, one on parietal. Subtle CRI pulsation visible. Frontoparietal suture highlighted amber. CRI rhythm arrows. 10-second loop.", videoSrc:V("osteo-cranial-frontoparietal") },

  { id:"osteo-cranial-sphenobasilar-flexion", name:"Sphenobasilar Flexion Technique", region:"Cranium", techniqueType:"cranial", patientPosition:"Supine", therapistPosition:"At head of table", description:"SBJ flexion induction — therapist synchronizes with cranial flexion phase to encourage correction.", animationPrompt:"3D medical animation. Patient supine. Therapist holds occiput and sphenoid. CRI flexion phase amplified. SBJ highlighted amber. Flexion phase arrows. 10-second loop.", videoSrc:V("osteo-cranial-sphenobasilar-flexion") },

  { id:"osteo-cranial-sphenobasilar-extension", name:"Sphenobasilar Extension Technique", region:"Cranium", techniqueType:"cranial", patientPosition:"Supine", therapistPosition:"At head of table", description:"SBJ extension induction for extension strain pattern correction.", animationPrompt:"3D medical animation. Patient supine. Therapist holds cranium. CRI extension phase assisted. SBJ highlighted amber. Extension phase arrows. 10-second loop.", videoSrc:V("osteo-cranial-sphenobasilar-extension") },

  { id:"osteo-cranial-temporal-bone", name:"Temporal Bone Mobilization", region:"Cranium", techniqueType:"cranial", patientPosition:"Supine", therapistPosition:"At head of table", description:"Temporal bone ear-pull and internal rotation mobilization for TMD and hearing-related symptoms.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts temporal bones bilaterally. Gentle ER/IR mobilization. Temporal bones highlighted amber. Rotation arrows. 10-second loop.", videoSrc:V("osteo-cranial-temporal-bone") },

  { id:"osteo-cranial-sacrum-respiratory", name:"Craniosacral Sacrum Technique", region:"Cranium/Sacrum", techniqueType:"cranial", patientPosition:"Supine", therapistPosition:"Beside table + at sacrum", description:"CS rhythm palpation and correction at sacrum — whole-body craniosacral integration.", animationPrompt:"3D medical animation. Patient supine. One therapist hand at occiput, other at sacrum. CRI rhythm visible traveling entire CS axis. Sacrum highlighted amber. CS rhythm arrows. 10-second loop.", videoSrc:V("osteo-cranial-sacrum-respiratory") },

  { id:"osteo-cranial-cv4-compression", name:"CV4 Compression of 4th Ventricle", region:"Cranium", techniqueType:"cranial", patientPosition:"Supine", therapistPosition:"At head of table", description:"CV4 still point induction — reduces CRI amplitude to reset the craniosacral system.", animationPrompt:"3D medical animation. Patient supine. Therapist thumbs on occipital squama. Gentle medial compression induces still point. Occiput highlighted amber. Still point indicator. 10-second loop.", videoSrc:V("osteo-cranial-cv4-compression") },

  { id:"osteo-cranial-still-point-occipital", name:"Occipital Still Point Induction", region:"Cranium", techniqueType:"cranial", patientPosition:"Supine", therapistPosition:"At head of table", description:"Occipital still point — bilateral thumb pressure at occiput to arrest CRI and promote reset.", animationPrompt:"3D medical animation. Patient supine. Therapist thenar contacts lateral occiput. CRI arrests — still point shown. Occiput highlighted amber. Still point arrows. 10-second loop.", videoSrc:V("osteo-cranial-still-point-occipital") },

  { id:"osteo-cranial-frontal-bone-decompression", name:"Frontal Bone Decompression", region:"Cranium", techniqueType:"cranial", patientPosition:"Supine", therapistPosition:"At head of table", description:"Frontal bone decompression for sinusitis, frontal headache, and metopic suture restriction.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts frontal bone. Gentle superior-anterior decompression. Frontal bone highlighted amber. Decompression arrows. 10-second loop.", videoSrc:V("osteo-cranial-frontal-bone-decompression") },

  { id:"osteo-cranial-parietal-lift", name:"Parietal Lift", region:"Cranium", techniqueType:"cranial", patientPosition:"Supine", therapistPosition:"At head of table", description:"Parietal lift technique for sagittal suture restriction and intracranial fluid normalization.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts parietal bones bilaterally. Gentle superior lift. Sagittal suture highlighted amber. Lift arrows. 10-second loop.", videoSrc:V("osteo-cranial-parietal-lift") },

  { id:"osteo-cranial-vomer-decompression", name:"Vomer Decompression", region:"Cranium", techniqueType:"cranial", patientPosition:"Supine", therapistPosition:"At head of table", description:"Vomer decompression for palatal restriction, mouth breathing, and sinus issues.", animationPrompt:"3D medical animation. Patient supine, mouth slightly open. Therapist thumb on palate contacts vomer. Gentle superior traction. Vomer highlighted amber. Decompression arrows. 10-second loop.", videoSrc:V("osteo-cranial-vomer-decompression") },

  { id:"osteo-cranial-mandible-release", name:"Mandible Release", region:"Cranium/TMJ", techniqueType:"cranial", patientPosition:"Supine", therapistPosition:"At head of table", description:"Mandibular release for TMD, bruxism, and trigeminal neuralgia.", animationPrompt:"3D medical animation. Patient supine. Therapist contacts mandible bilaterally. Gentle inferior traction and lateral correction. Mandible highlighted amber. Release arrows. 10-second loop.", videoSrc:V("osteo-cranial-mandible-release") },

  { id:"osteo-cranial-hyoid-release", name:"Hyoid Release", region:"Cervical", techniqueType:"cranial", patientPosition:"Supine", therapistPosition:"At head of table", description:"Hyoid bone release for dysphagia, globus sensation, and cervical fascial restriction.", animationPrompt:"3D medical animation. Patient supine. Therapist gently grasps hyoid between thumb and finger. Subtle lateral rocking. Hyoid highlighted amber. Release arrows. 10-second loop.", videoSrc:V("osteo-cranial-hyoid-release") },

  { id:"osteo-cranial-sphenoid-decompression", name:"Sphenoid Decompression", region:"Cranium", techniqueType:"cranial", patientPosition:"Supine", therapistPosition:"At head of table", description:"Sphenoid decompression for headache, visual disturbance, and SBJ strain patterns.", animationPrompt:"3D medical animation. Patient supine. Therapist thumb contacts greater wing of sphenoid. Gentle lateral traction. Sphenoid highlighted amber. Decompression arrows. 10-second loop.", videoSrc:V("osteo-cranial-sphenoid-decompression") },

  { id:"osteo-cranial-sacral-rocking", name:"Sacral Rocking", region:"Sacrum", techniqueType:"cranial", patientPosition:"Supine", therapistPosition:"Beside table", description:"Gentle sacral rocking for CRI assessment and normalization — entry-level craniosacral contact.", animationPrompt:"3D medical animation. Patient supine. Therapist hand cradles sacrum. Gentle rocking in CRI rhythm. Sacrum highlighted amber. CRI rhythm arrows. 10-second loop.", videoSrc:V("osteo-cranial-sacral-rocking") },

  { id:"osteo-cranial-dural-tube-traction", name:"Dural Tube Traction", region:"Cranium/Spine", techniqueType:"cranial", patientPosition:"Supine", therapistPosition:"At head + beside table", description:"Dural tube traction technique — one hand at occiput, one at sacrum applying gentle longitudinal traction.", animationPrompt:"3D medical animation. Patient supine. Therapist hands at occiput and sacrum. Gentle longitudinal traction. Dural tube highlighted amber along spine. Traction arrows. 10-second loop.", videoSrc:V("osteo-cranial-dural-tube-traction") },

];

export const OSTEOPATHY_COUNT = OSTEOPATHY_REGISTRY.length;
