/**
 * VIDEO MAP — Exercise ID → MP4 video path
 * ─────────────────────────────────────────────────────────────────────────────
 * All exercise demonstration videos are stored in /public/exercise-videos/
 * Naming convention: {exercise-id}.mp4
 *
 * Videos are generated via the 3D animation pipeline using the animationPrompt
 * field in exerciseRegistry.ts and osteopathyRegistry.ts.
 *
 * HOW TO ADD A NEW VIDEO:
 *   1. Generate the MP4 using the animationPrompt from the exercise registry
 *   2. Place the file in /public/exercise-videos/{exercise-id}.mp4
 *   3. The VIDEO_MAP entry is already pre-populated — no code change needed
 *
 * ─────────────────────────────────────────────────────────────────────────────
 */

const BASE = "/exercise-videos";

function v(id: string): string {
  return `${BASE}/${id}.mp4`;
}

// ─── VIDEO MAP ────────────────────────────────────────────────────────────────
// Pre-populated with all exercise IDs. Videos become active once the MP4 file
// exists at the path. ExerciseVideoPlayer handles missing files gracefully.
// ─────────────────────────────────────────────────────────────────────────────

export const VIDEO_MAP: Record<string, string> = {

  // ── EXISTING EXERCISES (from exercises/page.tsx) ──────────────────────────
  "shoulder-external-rotation":        v("shoulder-external-rotation"),
  "bird-dog":                          v("bird-dog"),
  "hip-flexor-stretch":                v("hip-flexor-stretch"),
  "resistance-band-row":               v("resistance-band-row"),
  "dumbbell-lateral-raise":            v("dumbbell-lateral-raise"),
  "glute-bridge":                      v("glute-bridge"),
  "dead-bug":                          v("dead-bug"),
  "plank":                             v("plank"),
  "cervical-retraction":               v("cervical-retraction"),
  "ankle-pumps":                       v("ankle-pumps"),
  "squat":                             v("squat"),
  "seated-knee-extension":             v("seated-knee-extension"),
  "side-lying-hip-abduction":          v("side-lying-hip-abduction"),
  "rdl":                               v("rdl"),
  "mckenzie-press":                    v("mckenzie-press"),
  "knee-to-chest":                     v("knee-to-chest"),
  "foam-roller-thoracic":              v("foam-roller-thoracic"),
  "pelvic-tilt":                       v("pelvic-tilt"),
  "lunge":                             v("lunge"),
  "calf-raise":                        v("calf-raise"),
  "shoulder-pendulum":                 v("shoulder-pendulum"),
  "wall-angel":                        v("wall-angel"),
  "step-up":                           v("step-up"),
  "cat-cow":                           v("cat-cow"),

  // ── CERVICAL SPINE (25) ───────────────────────────────────────────────────
  "cervical-side-flexion-stretch":     v("cervical-side-flexion-stretch"),
  "cervical-rotation-active":          v("cervical-rotation-active"),
  "suboccipital-release":              v("suboccipital-release"),
  "cervical-isometric-flexion":        v("cervical-isometric-flexion"),
  "cervical-isometric-extension":      v("cervical-isometric-extension"),
  "cervical-isometric-rotation":       v("cervical-isometric-rotation"),
  "cervical-isometric-side-flex":      v("cervical-isometric-side-flex"),
  "levator-scapulae-stretch":          v("levator-scapulae-stretch"),
  "upper-trap-stretch":                v("upper-trap-stretch"),
  "sternocleidomastoid-stretch":       v("sternocleidomastoid-stretch"),
  "cervical-flexion-range":            v("cervical-flexion-range"),
  "cervical-extension-range":          v("cervical-extension-range"),
  "cervical-axial-rotation-drill":     v("cervical-axial-rotation-drill"),
  "chin-tuck-supine":                  v("chin-tuck-supine"),
  "chin-tuck-against-wall":            v("chin-tuck-against-wall"),
  "neck-strengthening-prone":          v("neck-strengthening-prone"),
  "cervical-dns-pattern":              v("cervical-dns-pattern"),
  "scalene-stretch":                   v("scalene-stretch"),
  "cervical-mobility-flow":            v("cervical-mobility-flow"),
  "thoracic-cervical-junction-mob":    v("thoracic-cervical-junction-mob"),
  "longus-colli-activation":           v("longus-colli-activation"),
  "cervical-pnf-d1":                   v("cervical-pnf-d1"),
  "vestibular-gaze-stability":         v("vestibular-gaze-stability"),
  "cervical-band-resistance":          v("cervical-band-resistance"),
  "cervical-foam-roller-release":      v("cervical-foam-roller-release"),

  // ── THORACIC SPINE (25) ───────────────────────────────────────────────────
  "thoracic-extension-chair":          v("thoracic-extension-chair"),
  "thoracic-rotation-seated":          v("thoracic-rotation-seated"),
  "thoracic-rotation-quadruped":       v("thoracic-rotation-quadruped"),
  "book-opening-stretch":              v("book-opening-stretch"),
  "thread-the-needle":                 v("thread-the-needle"),
  "thoracic-cat-cow":                  v("thoracic-cat-cow"),
  "thoracic-side-flexion":             v("thoracic-side-flexion"),
  "pec-minor-stretch-doorway":         v("pec-minor-stretch-doorway"),
  "thoracic-foam-roller-segmental":    v("thoracic-foam-roller-segmental"),
  "thoracic-extension-foam-roller":    v("thoracic-extension-foam-roller"),
  "rhomboid-row-band":                 v("rhomboid-row-band"),
  "mid-trap-prone-yw":                 v("mid-trap-prone-yw"),
  "serratus-anterior-push-plus":       v("serratus-anterior-push-plus"),
  "thoracic-pnf-rotation":             v("thoracic-pnf-rotation"),
  "standing-rib-expansion":            v("standing-rib-expansion"),
  "diaphragmatic-breathing-lateral":   v("diaphragmatic-breathing-lateral"),
  "thoracic-extension-prone":          v("thoracic-extension-prone"),
  "kyphosis-correction-wall":          v("kyphosis-correction-wall"),
  "serratus-wall-slide":               v("serratus-wall-slide"),
  "lower-trap-activation-prone":       v("lower-trap-activation-prone"),
  "thoracic-open-book-seated":         v("thoracic-open-book-seated"),
  "costal-breathing-3d":               v("costal-breathing-3d"),
  "thoracic-band-pull-apart":          v("thoracic-band-pull-apart"),
  "shoulder-blade-squeeze":            v("shoulder-blade-squeeze"),
  "thoracic-windmill":                 v("thoracic-windmill"),

  // ── LUMBAR SPINE (30) ─────────────────────────────────────────────────────
  "lumbar-multifidus-activation":      v("lumbar-multifidus-activation"),
  "prone-hip-extension":               v("prone-hip-extension"),
  "side-plank":                        v("side-plank"),
  "side-plank-hip-abduction":          v("side-plank-hip-abduction"),
  "prone-plank":                       v("prone-plank"),
  "pallof-press":                      v("pallof-press"),
  "deadbug-advanced":                  v("deadbug-advanced"),
  "bird-dog-advanced":                 v("bird-dog-advanced"),
  "lumbar-flexion-stretch-supine":     v("lumbar-flexion-stretch-supine"),
  "piriformis-stretch":                v("piriformis-stretch"),
  "lumbar-segmental-mobility":         v("lumbar-segmental-mobility"),
  "quadratus-lumborum-stretch":        v("quadratus-lumborum-stretch"),
  "trunk-rotation-supine":             v("trunk-rotation-supine"),
  "lumbar-extension-prone-press":      v("lumbar-extension-prone-press"),
  "suitcase-carry":                    v("suitcase-carry"),
  "farmers-carry":                     v("farmers-carry"),
  "single-leg-deadlift-bodyweight":    v("single-leg-deadlift-bodyweight"),
  "good-morning-band":                 v("good-morning-band"),
  "back-extension-bench":              v("back-extension-bench"),
  "reverse-hyperextension":            v("reverse-hyperextension"),
  "cobra-stretch":                     v("cobra-stretch"),
  "childs-pose":                       v("childs-pose"),
  "seated-forward-fold":               v("seated-forward-fold"),
  "supine-twist":                      v("supine-twist"),
  "lumbar-mobilization-band":          v("lumbar-mobilization-band"),
  "lumbar-traction-self":              v("lumbar-traction-self"),
  "four-point-breathing-expansion":    v("four-point-breathing-expansion"),
  "hip-hinge-pattern":                 v("hip-hinge-pattern"),
  "lumbar-nerve-flossing":             v("lumbar-nerve-flossing"),
  "sciatic-nerve-slider":              v("sciatic-nerve-slider"),

  // ── SHOULDER (40) ─────────────────────────────────────────────────────────
  "shoulder-internal-rotation-band":   v("shoulder-internal-rotation-band"),
  "shoulder-abduction-band":           v("shoulder-abduction-band"),
  "shoulder-flexion-band":             v("shoulder-flexion-band"),
  "shoulder-scaption-band":            v("shoulder-scaption-band"),
  "diagonal-pattern-d1":               v("diagonal-pattern-d1"),
  "diagonal-pattern-d2":               v("diagonal-pattern-d2"),
  "prone-yw-exercise":                 v("prone-yw-exercise"),
  "prone-horizontal-abduction":        v("prone-horizontal-abduction"),
  "side-lying-external-rotation":      v("side-lying-external-rotation"),
  "subscapularis-activation":          v("subscapularis-activation"),
  "empty-can-test-exercise":           v("empty-can-test-exercise"),
  "full-can-exercise":                 v("full-can-exercise"),
  "shoulder-ir-behind-back-stretch":   v("shoulder-ir-behind-back-stretch"),
  "cross-body-shoulder-stretch":       v("cross-body-shoulder-stretch"),
  "sleeper-stretch":                   v("sleeper-stretch"),
  "doorway-pec-stretch":               v("doorway-pec-stretch"),
  "shoulder-cam-mobilization":         v("shoulder-cam-mobilization"),
  "inferior-capsule-stretch":          v("inferior-capsule-stretch"),
  "ac-joint-compression-relief":       v("ac-joint-compression-relief"),
  "bicep-curl-band":                   v("bicep-curl-band"),
  "tricep-extension-band":             v("tricep-extension-band"),
  "push-up-plus":                      v("push-up-plus"),
  "push-up-progression":               v("push-up-progression"),
  "shoulder-press-standing-band":      v("shoulder-press-standing-band"),
  "shoulder-rotator-cuff-circuit":     v("shoulder-rotator-cuff-circuit"),
  "shoulder-pnf-d1-extension":         v("shoulder-pnf-d1-extension"),
  "shoulder-pnf-d2-flexion":           v("shoulder-pnf-d2-flexion"),
  "shoulder-blade-clock":              v("shoulder-blade-clock"),
  "shoulder-posterior-capsule-mob":    v("shoulder-posterior-capsule-mob"),
  "overhead-reach-mobilization":       v("overhead-reach-mobilization"),
  "shoulder-band-distraction":         v("shoulder-band-distraction"),
  "shoulder-proprioception-ball":      v("shoulder-proprioception-ball"),
  "rotator-cuff-eccentric":            v("rotator-cuff-eccentric"),
  "shoulder-isokinetic-arc":           v("shoulder-isokinetic-arc"),
  "throwing-deceleration-drill":       v("throwing-deceleration-drill"),
  "wall-push-up-serratus":             v("wall-push-up-serratus"),
  "shoulder-joint-mobilization-band":  v("shoulder-joint-mobilization-band"),
  "acromioplasty-rehab-protocol":      v("acromioplasty-rehab-protocol"),
  "shoulder-stability-plank":          v("shoulder-stability-plank"),
  "rotator-cuff-isometrics-set":       v("rotator-cuff-isometrics-set"),

  // ── ELBOW (20) ────────────────────────────────────────────────────────────
  "elbow-flexion-curls-band":          v("elbow-flexion-curls-band"),
  "elbow-extension-triceps-band":      v("elbow-extension-triceps-band"),
  "wrist-flexor-stretch-elbow":        v("wrist-flexor-stretch-elbow"),
  "wrist-extensor-stretch-elbow":      v("wrist-extensor-stretch-elbow"),
  "pronation-supination-band":         v("pronation-supination-band"),
  "eccentric-wrist-extension":         v("eccentric-wrist-extension"),
  "eccentric-wrist-flexion":           v("eccentric-wrist-flexion"),
  "lateral-epicondyle-stretch":        v("lateral-epicondyle-stretch"),
  "medial-epicondyle-stretch":         v("medial-epicondyle-stretch"),
  "elbow-nerve-flossing-radial":       v("elbow-nerve-flossing-radial"),
  "elbow-nerve-flossing-ulnar":        v("elbow-nerve-flossing-ulnar"),
  "elbow-nerve-flossing-median":       v("elbow-nerve-flossing-median"),
  "golfers-elbow-eccentric":           v("golfers-elbow-eccentric"),
  "tennis-elbow-eccentric":            v("tennis-elbow-eccentric"),
  "elbow-joint-mobilization":          v("elbow-joint-mobilization"),
  "biceps-eccentric-curl":             v("biceps-eccentric-curl"),
  "triceps-eccentric-extension":       v("triceps-eccentric-extension"),
  "elbow-extension-isometric":         v("elbow-extension-isometric"),
  "elbow-flexion-isometric":           v("elbow-flexion-isometric"),
  "elbow-proprioception-catch":        v("elbow-proprioception-catch"),

  // ── WRIST / HAND (15) ─────────────────────────────────────────────────────
  "wrist-flexion-extension-active":    v("wrist-flexion-extension-active"),
  "wrist-radial-ulnar-deviation":      v("wrist-radial-ulnar-deviation"),
  "wrist-circumduction":               v("wrist-circumduction"),
  "finger-tendon-gliding":             v("finger-tendon-gliding"),
  "finger-intrinsic-exercises":        v("finger-intrinsic-exercises"),
  "thumb-opposition-drill":            v("thumb-opposition-drill"),
  "grip-strengthening-putty":          v("grip-strengthening-putty"),
  "pinch-grip-strengthening":          v("pinch-grip-strengthening"),
  "wrist-extension-strengthening":     v("wrist-extension-strengthening"),
  "wrist-flexion-strengthening":       v("wrist-flexion-strengthening"),
  "carpal-tunnel-nerve-gliding":       v("carpal-tunnel-nerve-gliding"),
  "de-quervain-stretch":               v("de-quervain-stretch"),
  "wrist-eccentric-extension":         v("wrist-eccentric-extension"),
  "forearm-myofascial-release":        v("forearm-myofascial-release"),
  "hand-opening-closing-band":         v("hand-opening-closing-band"),

  // ── HIP (35) ──────────────────────────────────────────────────────────────
  "hip-abduction-standing-band":       v("hip-abduction-standing-band"),
  "hip-adduction-band":                v("hip-adduction-band"),
  "hip-extension-standing-band":       v("hip-extension-standing-band"),
  "clamshell-band":                    v("clamshell-band"),
  "fire-hydrant":                      v("fire-hydrant"),
  "donkey-kick":                       v("donkey-kick"),
  "hip-thrust-bodyweight":             v("hip-thrust-bodyweight"),
  "hip-thrust-single-leg":             v("hip-thrust-single-leg"),
  "sumo-squat-wide":                   v("sumo-squat-wide"),
  "lateral-band-walk":                 v("lateral-band-walk"),
  "monster-walk-band":                 v("monster-walk-band"),
  "hip-90-90-stretch":                 v("hip-90-90-stretch"),
  "pigeon-pose-stretch":               v("pigeon-pose-stretch"),
  "frog-stretch":                      v("frog-stretch"),
  "couch-stretch-hip-flexor":          v("couch-stretch-hip-flexor"),
  "hip-ir-stretch-prone":              v("hip-ir-stretch-prone"),
  "hip-er-stretch-seated":             v("hip-er-stretch-seated"),
  "standing-hip-ir-mobilization":      v("standing-hip-ir-mobilization"),
  "standing-hip-er-mobilization":      v("standing-hip-er-mobilization"),
  "hip-capsule-mobilization-band":     v("hip-capsule-mobilization-band"),
  "hip-labrum-rehab-clamshell":        v("hip-labrum-rehab-clamshell"),
  "hip-labrum-rehab-abduction":        v("hip-labrum-rehab-abduction"),
  "femoral-acetabular-traction":       v("femoral-acetabular-traction"),
  "hip-flexor-eccentric":              v("hip-flexor-eccentric"),
  "gluteus-medius-side-plank-hip":     v("gluteus-medius-side-plank-hip"),
  "hip-hinge-single-leg":              v("hip-hinge-single-leg"),
  "reverse-lunge-hip":                 v("reverse-lunge-hip"),
  "lateral-lunge":                     v("lateral-lunge"),
  "curtsy-lunge":                      v("curtsy-lunge"),
  "hip-adductor-eccentric":            v("hip-adductor-eccentric"),
  "hip-pnf-flexion-abduction":         v("hip-pnf-flexion-abduction"),
  "hip-pnf-extension-adduction":       v("hip-pnf-extension-adduction"),
  "hip-posterior-chain-series":        v("hip-posterior-chain-series"),
  "hip-stability-single-leg-stand":    v("hip-stability-single-leg-stand"),
  "hip-proprioception-reach":          v("hip-proprioception-reach"),

  // ── KNEE (40) ─────────────────────────────────────────────────────────────
  "quad-sets-isometric":               v("quad-sets-isometric"),
  "terminal-knee-extension-band":      v("terminal-knee-extension-band"),
  "knee-flexion-prone-active":         v("knee-flexion-prone-active"),
  "straight-leg-raise":                v("straight-leg-raise"),
  "short-arc-quad":                    v("short-arc-quad"),
  "standing-quad-stretch":             v("standing-quad-stretch"),
  "standing-hamstring-stretch":        v("standing-hamstring-stretch"),
  "supine-hamstring-stretch-band":     v("supine-hamstring-stretch-band"),
  "wall-squat-isometric":              v("wall-squat-isometric"),
  "mini-squat-progression":            v("mini-squat-progression"),
  "step-down-eccentric":               v("step-down-eccentric"),
  "eccentric-squat-slow":              v("eccentric-squat-slow"),
  "single-leg-squat":                  v("single-leg-squat"),
  "bulgarian-split-squat":             v("bulgarian-split-squat"),
  "knee-extension-open-chain":         v("knee-extension-open-chain"),
  "knee-flexion-hamstring-curl-band":  v("knee-flexion-hamstring-curl-band"),
  "nordic-hamstring-curl":             v("nordic-hamstring-curl"),
  "patella-glide-mobilization":        v("patella-glide-mobilization"),
  "patellar-taping-technique":         v("patellar-taping-technique"),
  "vastus-medialis-activation":        v("vastus-medialis-activation"),
  "knee-proprioception-wobble":        v("knee-proprioception-wobble"),
  "knee-stability-lateral-band":       v("knee-stability-lateral-band"),
  "iliotibial-band-stretch":           v("iliotibial-band-stretch"),
  "foam-roller-it-band":               v("foam-roller-it-band"),
  "foam-roller-quads":                 v("foam-roller-quads"),
  "foam-roller-hamstrings":            v("foam-roller-hamstrings"),
  "acl-rehab-phase1":                  v("acl-rehab-phase1"),
  "acl-rehab-phase2-perturbation":     v("acl-rehab-phase2-perturbation"),
  "meniscus-rehab-loading":            v("meniscus-rehab-loading"),
  "knee-pnf-extension-pattern":        v("knee-pnf-extension-pattern"),
  "pca-rehab-quad-activation":         v("pca-rehab-quad-activation"),
  "knee-nerve-flossing-femoral":       v("knee-nerve-flossing-femoral"),
  "knee-nerve-flossing-sciatic":       v("knee-nerve-flossing-sciatic"),
  "pes-anserinus-stretch":             v("pes-anserinus-stretch"),
  "knee-joint-mobilization-band":      v("knee-joint-mobilization-band"),
  "box-squat":                         v("box-squat"),
  "goblet-squat-band":                 v("goblet-squat-band"),
  "lateral-step-up-band":              v("lateral-step-up-band"),
  "reverse-step-down":                 v("reverse-step-down"),
  "knee-plyometric-hop":               v("knee-plyometric-hop"),

  // ── ANKLE / FOOT (25) ─────────────────────────────────────────────────────
  "ankle-dorsiflexion-mobilization":   v("ankle-dorsiflexion-mobilization"),
  "ankle-plantar-flexion-active":      v("ankle-plantar-flexion-active"),
  "ankle-inversion-band":              v("ankle-inversion-band"),
  "ankle-eversion-band":               v("ankle-eversion-band"),
  "ankle-circles-active":              v("ankle-circles-active"),
  "ankle-alphabet-exercise":           v("ankle-alphabet-exercise"),
  "single-leg-calf-raise-eccentric":   v("single-leg-calf-raise-eccentric"),
  "soleus-calf-raise-bent-knee":       v("soleus-calf-raise-bent-knee"),
  "ankle-band-dorsiflexion":           v("ankle-band-dorsiflexion"),
  "heel-walk-dorsiflexion":            v("heel-walk-dorsiflexion"),
  "toe-walk":                          v("toe-walk"),
  "ankle-proprioception-single-leg":   v("ankle-proprioception-single-leg"),
  "ankle-wobble-board":                v("ankle-wobble-board"),
  "star-excursion-balance":            v("star-excursion-balance"),
  "plantar-fascia-stretch":            v("plantar-fascia-stretch"),
  "intrinsic-foot-muscles-dome":       v("intrinsic-foot-muscles-dome"),
  "short-foot-exercise":               v("short-foot-exercise"),
  "toe-curl-towel":                    v("toe-curl-towel"),
  "big-toe-extension-mobilization":    v("big-toe-extension-mobilization"),
  "heel-toe-walking":                  v("heel-toe-walking"),
  "ankle-sprain-rehab-phase1":         v("ankle-sprain-rehab-phase1"),
  "ankle-sprain-rehab-phase2":         v("ankle-sprain-rehab-phase2"),
  "achilles-eccentric-decline":        v("achilles-eccentric-decline"),
  "peroneal-strengthening-band":       v("peroneal-strengthening-band"),
  "subtalar-mobilization":             v("subtalar-mobilization"),

  // ── CORE (30) ─────────────────────────────────────────────────────────────
  "hollow-body-hold":                  v("hollow-body-hold"),
  "plank-shoulder-tap":                v("plank-shoulder-tap"),
  "plank-hip-dip":                     v("plank-hip-dip"),
  "copenhagen-plank":                  v("copenhagen-plank"),
  "reverse-crunch":                    v("reverse-crunch"),
  "ab-rollout-band":                   v("ab-rollout-band"),
  "hanging-knee-raise":                v("hanging-knee-raise"),
  "v-sit-progression":                 v("v-sit-progression"),
  "oblique-crunch-side":               v("oblique-crunch-side"),
  "russian-twist":                     v("russian-twist"),
  "bicycle-crunch":                    v("bicycle-crunch"),
  "superman-hold-prone":               v("superman-hold-prone"),
  "pallof-press-rotation":             v("pallof-press-rotation"),
  "cable-chop-rotation":               v("cable-chop-rotation"),
  "cable-lift-rotation":               v("cable-lift-rotation"),
  "anti-rotation-band":                v("anti-rotation-band"),
  "core-stiffness-carry-overhead":     v("core-stiffness-carry-overhead"),
  "half-kneeling-pallof":              v("half-kneeling-pallof"),
  "tall-kneeling-pallof":              v("tall-kneeling-pallof"),
  "renegade-row-plank":                v("renegade-row-plank"),
  "bear-crawl":                        v("bear-crawl"),
  "crawl-pattern-dns":                 v("crawl-pattern-dns"),
  "hip-flexor-core-sitting-band":      v("hip-flexor-core-sitting-band"),
  "rollup-core":                       v("rollup-core"),
  "spinal-flexion-crunch-control":     v("spinal-flexion-crunch-control"),
  "side-plank-rotation":               v("side-plank-rotation"),
  "inchworm":                          v("inchworm"),
  "plank-to-downdog":                  v("plank-to-downdog"),
  "core-breathing-4-point":            v("core-breathing-4-point"),
  "hardstyle-plank":                   v("hardstyle-plank"),

  // ── FUNCTIONAL / SPORT REHAB (15) ────────────────────────────────────────
  "split-squat-jump":                  v("split-squat-jump"),
  "lateral-shuffle-band":              v("lateral-shuffle-band"),
  "single-leg-hop-forward":            v("single-leg-hop-forward"),
  "single-leg-hop-lateral":            v("single-leg-hop-lateral"),
  "deceleration-landing":              v("deceleration-landing"),
  "cutting-change-direction":          v("cutting-change-direction"),
  "squat-jump-landing-mechanics":      v("squat-jump-landing-mechanics"),
  "hip-drop-pelvic-control-running":   v("hip-drop-pelvic-control-running"),
  "running-gait-retraining":           v("running-gait-retraining"),
  "shoulder-throwing-progression":     v("shoulder-throwing-progression"),
  "overhead-athlete-series":           v("overhead-athlete-series"),
  "rotational-power-med-ball":         v("rotational-power-med-ball"),
  "band-sprint-resisted":              v("band-sprint-resisted"),
  "agility-ladder-basic":              v("agility-ladder-basic"),
  "return-to-sport-criteria":          v("return-to-sport-criteria"),

  // ── OSTEOPATHY TECHNIQUES (120) ───────────────────────────────────────────
  // Joint Mobilization (25)
  "osteo-cervical-mob-c0-c1":                 v("osteo-cervical-mob-c0-c1"),
  "osteo-cervical-mob-c1-c2":                 v("osteo-cervical-mob-c1-c2"),
  "osteo-cervical-mob-c2-c7":                 v("osteo-cervical-mob-c2-c7"),
  "osteo-thoracic-mob-t1-t4":                 v("osteo-thoracic-mob-t1-t4"),
  "osteo-thoracic-mob-t4-t8":                 v("osteo-thoracic-mob-t4-t8"),
  "osteo-thoracic-mob-t8-t12":                v("osteo-thoracic-mob-t8-t12"),
  "osteo-lumbar-mob-l1-l5":                   v("osteo-lumbar-mob-l1-l5"),
  "osteo-sacroiliac-mob":                     v("osteo-sacroiliac-mob"),
  "osteo-shoulder-glenohumeral-mob":          v("osteo-shoulder-glenohumeral-mob"),
  "osteo-shoulder-acromioclavicular-mob":     v("osteo-shoulder-acromioclavicular-mob"),
  "osteo-elbow-radiohumeral-mob":             v("osteo-elbow-radiohumeral-mob"),
  "osteo-elbow-proximal-radioulnar-mob":      v("osteo-elbow-proximal-radioulnar-mob"),
  "osteo-wrist-radiocarpal-mob":              v("osteo-wrist-radiocarpal-mob"),
  "osteo-hip-mob-anterior-glide":             v("osteo-hip-mob-anterior-glide"),
  "osteo-hip-mob-posterior-glide":            v("osteo-hip-mob-posterior-glide"),
  "osteo-hip-mob-lateral-distraction":        v("osteo-hip-mob-lateral-distraction"),
  "osteo-knee-tibiofemoral-mob":              v("osteo-knee-tibiofemoral-mob"),
  "osteo-knee-patellofemoral-mob":            v("osteo-knee-patellofemoral-mob"),
  "osteo-ankle-talocrural-mob":               v("osteo-ankle-talocrural-mob"),
  "osteo-ankle-subtalar-mob":                 v("osteo-ankle-subtalar-mob"),
  "osteo-first-metatarsophalangeal-mob":      v("osteo-first-metatarsophalangeal-mob"),
  "osteo-rib-mob-anterior":                   v("osteo-rib-mob-anterior"),
  "osteo-rib-mob-posterior":                  v("osteo-rib-mob-posterior"),
  "osteo-clavicle-sternoclavicular-mob":      v("osteo-clavicle-sternoclavicular-mob"),
  "osteo-tmj-mob":                            v("osteo-tmj-mob"),
  // HVLA (20)
  "osteo-hvla-cervical-rotation":             v("osteo-hvla-cervical-rotation"),
  "osteo-hvla-cervical-flexion-rotation":     v("osteo-hvla-cervical-flexion-rotation"),
  "osteo-hvla-upper-thoracic":                v("osteo-hvla-upper-thoracic"),
  "osteo-hvla-mid-thoracic-sitting":          v("osteo-hvla-mid-thoracic-sitting"),
  "osteo-hvla-mid-thoracic-supine":           v("osteo-hvla-mid-thoracic-supine"),
  "osteo-hvla-lower-thoracic":                v("osteo-hvla-lower-thoracic"),
  "osteo-hvla-lumbar-sidebending":            v("osteo-hvla-lumbar-sidebending"),
  "osteo-hvla-lumbar-rotation":               v("osteo-hvla-lumbar-rotation"),
  "osteo-hvla-sacroiliac-posterior":          v("osteo-hvla-sacroiliac-posterior"),
  "osteo-hvla-sacroiliac-anterior":           v("osteo-hvla-sacroiliac-anterior"),
  "osteo-hvla-sacrum-shear":                  v("osteo-hvla-sacrum-shear"),
  "osteo-hvla-pubic-symphysis":               v("osteo-hvla-pubic-symphysis"),
  "osteo-hvla-rib-pump-supine":               v("osteo-hvla-rib-pump-supine"),
  "osteo-hvla-rib-sitting":                   v("osteo-hvla-rib-sitting"),
  "osteo-hvla-hip-scouring":                  v("osteo-hvla-hip-scouring"),
  "osteo-hvla-elbow-lateral-gap":             v("osteo-hvla-elbow-lateral-gap"),
  "osteo-hvla-wrist-carpal":                  v("osteo-hvla-wrist-carpal"),
  "osteo-hvla-ankle-mortise":                 v("osteo-hvla-ankle-mortise"),
  "osteo-hvla-cuboid-notch":                  v("osteo-hvla-cuboid-notch"),
  "osteo-hvla-first-rib":                     v("osteo-hvla-first-rib"),
  // Muscle Energy (25)
  "osteo-met-cervical-flexion":               v("osteo-met-cervical-flexion"),
  "osteo-met-cervical-extension":             v("osteo-met-cervical-extension"),
  "osteo-met-cervical-rotation":              v("osteo-met-cervical-rotation"),
  "osteo-met-cervical-sidebend":              v("osteo-met-cervical-sidebend"),
  "osteo-met-thoracic-rotation":              v("osteo-met-thoracic-rotation"),
  "osteo-met-thoracic-extension":             v("osteo-met-thoracic-extension"),
  "osteo-met-lumbar-rotation":                v("osteo-met-lumbar-rotation"),
  "osteo-met-lumbar-extension":               v("osteo-met-lumbar-extension"),
  "osteo-met-sacroiliac-iliac-anterior":      v("osteo-met-sacroiliac-iliac-anterior"),
  "osteo-met-sacroiliac-iliac-posterior":     v("osteo-met-sacroiliac-iliac-posterior"),
  "osteo-met-piriformis":                     v("osteo-met-piriformis"),
  "osteo-met-psoas":                          v("osteo-met-psoas"),
  "osteo-met-quadratus-lumborum":             v("osteo-met-quadratus-lumborum"),
  "osteo-met-hamstrings":                     v("osteo-met-hamstrings"),
  "osteo-met-adductors":                      v("osteo-met-adductors"),
  "osteo-met-shoulder-internal-rotation":     v("osteo-met-shoulder-internal-rotation"),
  "osteo-met-shoulder-external-rotation":     v("osteo-met-shoulder-external-rotation"),
  "osteo-met-shoulder-elevation":             v("osteo-met-shoulder-elevation"),
  "osteo-met-elbow-flexion":                  v("osteo-met-elbow-flexion"),
  "osteo-met-ankle-plantarflexion":           v("osteo-met-ankle-plantarflexion"),
  "osteo-met-ankle-dorsiflexion":             v("osteo-met-ankle-dorsiflexion"),
  "osteo-met-ribs-exhalation":                v("osteo-met-ribs-exhalation"),
  "osteo-met-ribs-inhalation":                v("osteo-met-ribs-inhalation"),
  "osteo-met-upper-trap":                     v("osteo-met-upper-trap"),
  "osteo-met-levator-scapulae":               v("osteo-met-levator-scapulae"),
  // Myofascial Release (20)
  "osteo-mfr-thoracolumbar-fascia":           v("osteo-mfr-thoracolumbar-fascia"),
  "osteo-mfr-cervical-fascia":                v("osteo-mfr-cervical-fascia"),
  "osteo-mfr-suboccipital":                   v("osteo-mfr-suboccipital"),
  "osteo-mfr-diaphragm":                      v("osteo-mfr-diaphragm"),
  "osteo-mfr-pelvic-floor":                   v("osteo-mfr-pelvic-floor"),
  "osteo-mfr-iliotibial-band":                v("osteo-mfr-iliotibial-band"),
  "osteo-mfr-psoas-release":                  v("osteo-mfr-psoas-release"),
  "osteo-mfr-piriformis-release":             v("osteo-mfr-piriformis-release"),
  "osteo-mfr-quadratus-lumborum":             v("osteo-mfr-quadratus-lumborum"),
  "osteo-mfr-upper-trapezius":                v("osteo-mfr-upper-trapezius"),
  "osteo-mfr-sternocleidomastoid":            v("osteo-mfr-sternocleidomastoid"),
  "osteo-mfr-scalenes":                       v("osteo-mfr-scalenes"),
  "osteo-mfr-anterior-shoulder":              v("osteo-mfr-anterior-shoulder"),
  "osteo-mfr-posterior-shoulder":             v("osteo-mfr-posterior-shoulder"),
  "osteo-mfr-lateral-thigh":                  v("osteo-mfr-lateral-thigh"),
  "osteo-mfr-medial-knee":                    v("osteo-mfr-medial-knee"),
  "osteo-mfr-plantar-fascia":                 v("osteo-mfr-plantar-fascia"),
  "osteo-mfr-forearm-flexors":                v("osteo-mfr-forearm-flexors"),
  "osteo-mfr-forearm-extensors":              v("osteo-mfr-forearm-extensors"),
  "osteo-mfr-rib-intercostals":               v("osteo-mfr-rib-intercostals"),
  // Visceral (15)
  "osteo-visceral-liver-mob":                 v("osteo-visceral-liver-mob"),
  "osteo-visceral-stomach-mob":               v("osteo-visceral-stomach-mob"),
  "osteo-visceral-colon-mob":                 v("osteo-visceral-colon-mob"),
  "osteo-visceral-small-intestine-mob":       v("osteo-visceral-small-intestine-mob"),
  "osteo-visceral-kidney-ptosis":             v("osteo-visceral-kidney-ptosis"),
  "osteo-visceral-bladder-mob":               v("osteo-visceral-bladder-mob"),
  "osteo-visceral-uterine-mob":               v("osteo-visceral-uterine-mob"),
  "osteo-visceral-sigmoid-mob":               v("osteo-visceral-sigmoid-mob"),
  "osteo-visceral-cecum-mob":                 v("osteo-visceral-cecum-mob"),
  "osteo-visceral-diaphragm-dome":            v("osteo-visceral-diaphragm-dome"),
  "osteo-visceral-hiatal-hernia":             v("osteo-visceral-hiatal-hernia"),
  "osteo-visceral-ileocecal-valve":           v("osteo-visceral-ileocecal-valve"),
  "osteo-visceral-portal-liver":              v("osteo-visceral-portal-liver"),
  "osteo-visceral-gallbladder":               v("osteo-visceral-gallbladder"),
  "osteo-visceral-spleen":                    v("osteo-visceral-spleen"),
  // Cranial (15)
  "osteo-cranial-frontoparietal":             v("osteo-cranial-frontoparietal"),
  "osteo-cranial-sphenobasilar-flexion":      v("osteo-cranial-sphenobasilar-flexion"),
  "osteo-cranial-sphenobasilar-extension":    v("osteo-cranial-sphenobasilar-extension"),
  "osteo-cranial-temporal-bone":              v("osteo-cranial-temporal-bone"),
  "osteo-cranial-sacrum-respiratory":         v("osteo-cranial-sacrum-respiratory"),
  "osteo-cranial-cv4-compression":            v("osteo-cranial-cv4-compression"),
  "osteo-cranial-still-point-occipital":      v("osteo-cranial-still-point-occipital"),
  "osteo-cranial-frontal-bone-decompression": v("osteo-cranial-frontal-bone-decompression"),
  "osteo-cranial-parietal-lift":              v("osteo-cranial-parietal-lift"),
  "osteo-cranial-vomer-decompression":        v("osteo-cranial-vomer-decompression"),
  "osteo-cranial-mandible-release":           v("osteo-cranial-mandible-release"),
  "osteo-cranial-hyoid-release":              v("osteo-cranial-hyoid-release"),
  "osteo-cranial-sphenoid-decompression":     v("osteo-cranial-sphenoid-decompression"),
  "osteo-cranial-sacral-rocking":             v("osteo-cranial-sacral-rocking"),
  "osteo-cranial-dural-tube-traction":        v("osteo-cranial-dural-tube-traction"),
};

/**
 * Returns the video path for a given exercise/technique ID.
 * Returns undefined if the ID is not in the map.
 */
export function getVideoSrc(exerciseId: string): string | undefined {
  return VIDEO_MAP[exerciseId];
}
